alter table shift_attendance
    add column payment_status varchar(32) not null default 'UNPAID';

alter table shift_attendance
    add column paid_at timestamp with time zone;

alter table shift_attendance
    add constraint ck_shift_attendance_payment_status check (
        payment_status in ('UNPAID', 'PAYMENT_REQUESTED', 'PAID')
    );

create table payout_requests (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    worker_id bigint not null,
    manager_foreman_id bigint not null,
    status varchar(32) not null,
    raw_payable_minutes_total integer not null,
    payout_rounded_minutes_total integer not null,
    exact_calculated_amount_total numeric(12, 2) not null,
    payout_amount numeric(12, 0) not null,
    requested_at timestamp with time zone not null,
    approved_by bigint,
    approved_at timestamp with time zone,
    paid_at timestamp with time zone,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    constraint fk_payout_requests_company_id foreign key (company_id) references companies (id),
    constraint fk_payout_requests_worker_id foreign key (worker_id) references users (id),
    constraint fk_payout_requests_manager_foreman_id foreign key (manager_foreman_id) references users (id),
    constraint fk_payout_requests_approved_by foreign key (approved_by) references users (id),
    constraint ck_payout_requests_status check (status in ('PENDING', 'APPROVED')),
    constraint ck_payout_requests_raw_minutes check (raw_payable_minutes_total >= 0),
    constraint ck_payout_requests_rounded_minutes check (payout_rounded_minutes_total >= 0),
    constraint ck_payout_requests_exact_total check (exact_calculated_amount_total >= 0),
    constraint ck_payout_requests_payout_amount check (payout_amount >= 0),
    constraint ck_payout_requests_approved_state check (
        (status = 'PENDING' and approved_by is null and approved_at is null and paid_at is null)
        or (status = 'APPROVED' and approved_by is not null and approved_at is not null and paid_at is not null)
    )
);

create table payout_request_items (
    id bigint generated by default as identity primary key,
    payout_request_id bigint not null,
    attendance_id bigint not null,
    shift_session_id bigint not null,
    shift_title varchar(255) not null,
    shift_actual_start_time timestamp with time zone not null,
    shift_actual_end_time timestamp with time zone not null,
    raw_payable_minutes integer not null,
    payout_rounded_minutes integer not null,
    hourly_rate numeric(12, 2) not null,
    calculated_salary numeric(12, 2) not null,
    rounded_item_amount_exact numeric(12, 4) not null,
    payout_amount numeric(12, 0) not null,
    created_at timestamp with time zone not null default current_timestamp,
    paid_at timestamp with time zone,
    constraint fk_payout_request_items_request_id foreign key (payout_request_id) references payout_requests (id) on delete cascade,
    constraint fk_payout_request_items_attendance_id foreign key (attendance_id) references shift_attendance (id),
    constraint fk_payout_request_items_shift_session_id foreign key (shift_session_id) references shift_sessions (id),
    constraint uq_payout_request_items_attendance_id unique (attendance_id),
    constraint ck_payout_request_items_raw_minutes check (raw_payable_minutes >= 0),
    constraint ck_payout_request_items_rounded_minutes check (payout_rounded_minutes >= 0),
    constraint ck_payout_request_items_hourly_rate check (hourly_rate >= 0),
    constraint ck_payout_request_items_calculated_salary check (calculated_salary >= 0),
    constraint ck_payout_request_items_rounded_exact check (rounded_item_amount_exact >= 0),
    constraint ck_payout_request_items_payout_amount check (payout_amount >= 0)
);

create index idx_shift_attendance_payment_status on shift_attendance (payment_status);
create index idx_payout_requests_worker_status_requested_at on payout_requests (worker_id, status, requested_at);
create index idx_payout_requests_manager_status_requested_at on payout_requests (manager_foreman_id, status, requested_at);
create index idx_payout_requests_company_id on payout_requests (company_id);
create index idx_payout_request_items_request_id on payout_request_items (payout_request_id);
create index idx_payout_request_items_shift_session_id on payout_request_items (shift_session_id);
