alter table companies
    add column time_zone varchar(64);

update companies
set time_zone = '${default_timezone}'
where time_zone is null;

alter table companies
    alter column time_zone set not null;

alter table companies
    add constraint ck_companies_time_zone_not_blank check (length(trim(time_zone)) > 0);

create table pay_policies (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    current_version_id bigint,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    constraint uq_pay_policies_company_id unique (company_id),
    constraint fk_pay_policies_company_id foreign key (company_id) references companies (id) on delete cascade
);

create table pay_policy_versions (
    id bigint generated by default as identity primary key,
    pay_policy_id bigint not null,
    company_id bigint not null,
    version integer not null,
    week_starts_on varchar(16) not null,
    stacking_strategy varchar(32) not null,
    created_by bigint,
    created_at timestamp with time zone not null default current_timestamp,
    constraint uq_pay_policy_versions_policy_version unique (pay_policy_id, version),
    constraint fk_pay_policy_versions_policy_id foreign key (pay_policy_id) references pay_policies (id) on delete cascade,
    constraint fk_pay_policy_versions_company_id foreign key (company_id) references companies (id) on delete cascade,
    constraint fk_pay_policy_versions_created_by foreign key (created_by) references users (id),
    constraint ck_pay_policy_versions_version check (version > 0),
    constraint ck_pay_policy_versions_week_starts_on check (
        week_starts_on in ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')
    ),
    constraint ck_pay_policy_versions_stacking_strategy check (
        stacking_strategy in ('ADD', 'HIGHEST_ONLY')
    )
);

alter table pay_policies
    add constraint fk_pay_policies_current_version_id foreign key (current_version_id) references pay_policy_versions (id);

create table pay_policy_rules (
    id bigint generated by default as identity primary key,
    pay_policy_version_id bigint not null,
    name varchar(255) not null,
    type varchar(32) not null,
    enabled boolean not null,
    premium_percent numeric(14, 4) not null,
    condition_config text not null,
    sort_order integer not null,
    created_at timestamp with time zone not null default current_timestamp,
    constraint fk_pay_policy_rules_version_id foreign key (pay_policy_version_id) references pay_policy_versions (id) on delete cascade,
    constraint ck_pay_policy_rules_type check (
        type in ('TIME_OF_DAY', 'DAILY_OVERTIME', 'WEEKLY_OVERTIME', 'DAY_OF_WEEK', 'HOLIDAY')
    ),
    constraint ck_pay_policy_rules_premium_percent check (
        premium_percent >= 0 and premium_percent <= 1000
    ),
    constraint ck_pay_policy_rules_sort_order check (sort_order >= 0),
    constraint ck_pay_policy_rules_name_not_blank check (length(trim(name)) > 0),
    constraint ck_pay_policy_rules_condition_config_not_blank check (length(trim(condition_config)) > 0)
);

insert into pay_policies (company_id)
select companies.id
from companies
where not exists (
    select 1
    from pay_policies policies
    where policies.company_id = companies.id
);

insert into pay_policy_versions (
    pay_policy_id,
    company_id,
    version,
    week_starts_on,
    stacking_strategy,
    created_by
)
select policies.id,
       policies.company_id,
       1,
       'MONDAY',
       'ADD',
       null
from pay_policies policies
where not exists (
    select 1
    from pay_policy_versions policy_versions
    where policy_versions.pay_policy_id = policies.id
);

update pay_policies
set current_version_id = (
    select policy_versions.id
    from pay_policy_versions policy_versions
    where policy_versions.pay_policy_id = pay_policies.id
      and policy_versions.version = 1
)
where current_version_id is null;

alter table shift_sessions
    add column pay_policy_version_id bigint;

alter table shift_sessions
    add constraint fk_shift_sessions_pay_policy_version_id foreign key (pay_policy_version_id) references pay_policy_versions (id);

create index idx_pay_policy_versions_company_id on pay_policy_versions (company_id);
create index idx_pay_policy_versions_pay_policy_id on pay_policy_versions (pay_policy_id);
create index idx_pay_policy_rules_version_id on pay_policy_rules (pay_policy_version_id);
create index idx_shift_sessions_pay_policy_version_id on shift_sessions (pay_policy_version_id);
