create table pay_calculations (
    id bigint generated by default as identity primary key,
    attendance_id bigint not null,
    shift_session_id bigint not null,
    pay_policy_version_id bigint not null,
    total_raw_seconds numeric(18, 9) not null,
    total_raw_minutes_exact numeric(18, 8) not null,
    total_base_amount numeric(20, 8) not null,
    total_premium_amount numeric(20, 8) not null,
    total_amount numeric(20, 8) not null,
    created_at timestamp with time zone not null default current_timestamp,
    constraint uq_pay_calculations_attendance_id unique (attendance_id),
    constraint fk_pay_calculations_attendance_id foreign key (attendance_id) references shift_attendance (id) on delete cascade,
    constraint fk_pay_calculations_shift_session_id foreign key (shift_session_id) references shift_sessions (id) on delete cascade,
    constraint fk_pay_calculations_policy_version_id foreign key (pay_policy_version_id) references pay_policy_versions (id),
    constraint ck_pay_calculations_total_raw_seconds check (total_raw_seconds >= 0),
    constraint ck_pay_calculations_total_raw_minutes_exact check (total_raw_minutes_exact >= 0),
    constraint ck_pay_calculations_total_base_amount check (total_base_amount >= 0),
    constraint ck_pay_calculations_total_premium_amount check (total_premium_amount >= 0),
    constraint ck_pay_calculations_total_amount check (total_amount >= 0)
);

create table pay_segments (
    id bigint generated by default as identity primary key,
    pay_calculation_id bigint not null,
    segment_start timestamp with time zone not null,
    segment_end timestamp with time zone not null,
    payable_seconds numeric(18, 9) not null,
    payable_minutes bigint not null,
    payable_minutes_exact numeric(18, 8) not null,
    base_hourly_rate numeric(12, 2) not null,
    applied_rules_snapshot text not null,
    stacking_strategy varchar(32) not null,
    effective_premium_percent numeric(14, 4) not null,
    effective_hourly_rate numeric(14, 8) not null,
    base_amount numeric(20, 8) not null,
    premium_amount numeric(20, 8) not null,
    total_amount numeric(20, 8) not null,
    created_at timestamp with time zone not null default current_timestamp,
    constraint fk_pay_segments_calculation_id foreign key (pay_calculation_id) references pay_calculations (id) on delete cascade,
    constraint ck_pay_segments_order check (segment_end >= segment_start),
    constraint ck_pay_segments_payable_seconds check (payable_seconds >= 0),
    constraint ck_pay_segments_payable_minutes check (payable_minutes >= 0),
    constraint ck_pay_segments_payable_minutes_exact check (payable_minutes_exact >= 0),
    constraint ck_pay_segments_base_hourly_rate check (base_hourly_rate >= 0),
    constraint ck_pay_segments_applied_rules_snapshot_not_blank check (length(trim(applied_rules_snapshot)) > 0),
    constraint ck_pay_segments_stacking_strategy check (stacking_strategy in ('ADD', 'HIGHEST_ONLY')),
    constraint ck_pay_segments_effective_premium_percent check (
        effective_premium_percent >= 0 and effective_premium_percent <= 1000
    ),
    constraint ck_pay_segments_effective_hourly_rate check (effective_hourly_rate >= 0),
    constraint ck_pay_segments_base_amount check (base_amount >= 0),
    constraint ck_pay_segments_premium_amount check (premium_amount >= 0),
    constraint ck_pay_segments_total_amount check (total_amount >= 0)
);

create index idx_pay_calculations_shift_session_id on pay_calculations (shift_session_id);
create index idx_pay_calculations_policy_version_id on pay_calculations (pay_policy_version_id);
create index idx_pay_segments_calculation_id on pay_segments (pay_calculation_id);

alter table payout_requests
    add column total_base_amount numeric(20, 8);

alter table payout_requests
    add column total_premium_amount numeric(20, 8);

update payout_requests
set total_base_amount = exact_calculated_amount_total,
    total_premium_amount = 0;

alter table payout_requests
    alter column total_base_amount set not null;

alter table payout_requests
    alter column total_premium_amount set not null;

alter table payout_requests
    add constraint ck_payout_requests_total_base_amount check (total_base_amount >= 0);

alter table payout_requests
    add constraint ck_payout_requests_total_premium_amount check (total_premium_amount >= 0);

alter table payout_request_items
    add column total_base_amount numeric(20, 8);

alter table payout_request_items
    add column total_premium_amount numeric(20, 8);

update payout_request_items
set total_base_amount = calculated_salary,
    total_premium_amount = 0;

alter table payout_request_items
    alter column total_base_amount set not null;

alter table payout_request_items
    alter column total_premium_amount set not null;

alter table payout_request_items
    add constraint ck_payout_request_items_total_base_amount check (total_base_amount >= 0);

alter table payout_request_items
    add constraint ck_payout_request_items_total_premium_amount check (total_premium_amount >= 0);
