create table companies (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp
);
