create table shift_sessions (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    title varchar(255) not null,
    location varchar(255),
    join_code varchar(32) not null,
    status varchar(32) not null,
    planned_start_time timestamp with time zone,
    planned_end_time timestamp with time zone,
    actual_start_time timestamp with time zone,
    actual_end_time timestamp with time zone,
    default_break_minutes integer not null default 0,
    created_by bigint not null,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    constraint uq_shift_sessions_join_code unique (join_code),
    constraint fk_shift_sessions_company_id foreign key (company_id) references companies (id),
    constraint fk_shift_sessions_created_by foreign key (created_by) references users (id),
    constraint ck_shift_sessions_status check (status in ('CREATED', 'OPEN', 'ACTIVE', 'CLOSED', 'CANCELLED')),
    constraint ck_shift_sessions_default_break_minutes check (default_break_minutes >= 0),
    constraint ck_shift_sessions_planned_time_order check (
        planned_end_time is null
        or planned_start_time is null
        or planned_end_time >= planned_start_time
    ),
    constraint ck_shift_sessions_actual_time_order check (
        actual_end_time is null
        or actual_start_time is null
        or actual_end_time >= actual_start_time
    )
);

create index idx_shift_sessions_company_id on shift_sessions (company_id);
create index idx_shift_sessions_created_by on shift_sessions (created_by);
create index idx_shift_sessions_status on shift_sessions (status);
