create table shift_attendance (
    id bigint generated by default as identity primary key,
    shift_session_id bigint not null,
    worker_id bigint not null,
    status varchar(32) not null,
    hourly_rate numeric(12, 2) not null,
    break_minutes integer not null default 0,
    worked_minutes integer,
    calculated_salary numeric(12, 2),
    joined_at timestamp with time zone not null default current_timestamp,
    approved_at timestamp with time zone,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    constraint uq_shift_attendance_shift_worker unique (shift_session_id, worker_id),
    constraint fk_shift_attendance_shift_session_id foreign key (shift_session_id) references shift_sessions (id) on delete cascade,
    constraint fk_shift_attendance_worker_id foreign key (worker_id) references users (id),
    constraint ck_shift_attendance_status check (status in ('JOINED', 'APPROVED', 'REJECTED', 'CANCELLED')),
    constraint ck_shift_attendance_hourly_rate check (hourly_rate >= 0),
    constraint ck_shift_attendance_break_minutes check (break_minutes >= 0),
    constraint ck_shift_attendance_worked_minutes check (worked_minutes is null or worked_minutes >= 0),
    constraint ck_shift_attendance_calculated_salary check (calculated_salary is null or calculated_salary >= 0)
);

create index idx_shift_attendance_shift_session_id on shift_attendance (shift_session_id);
create index idx_shift_attendance_worker_id on shift_attendance (worker_id);
create index idx_shift_attendance_status on shift_attendance (status);
