alter table shift_attendance
    add column pause_minutes integer;

alter table shift_attendance
    add constraint ck_shift_attendance_pause_minutes check (
        pause_minutes is null or pause_minutes >= 0
    );

alter table shift_sessions
    add column foreman_pause_minutes integer;

alter table shift_sessions
    add constraint ck_shift_sessions_foreman_pause_minutes check (
        foreman_pause_minutes is null or foreman_pause_minutes >= 0
    );

create table shift_pause_intervals (
    id bigint generated by default as identity primary key,
    shift_session_id bigint not null,
    scope varchar(32) not null,
    user_id bigint,
    started_at timestamp with time zone not null,
    ended_at timestamp with time zone,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    constraint fk_shift_pause_intervals_shift_session_id foreign key (shift_session_id) references shift_sessions (id) on delete cascade,
    constraint fk_shift_pause_intervals_user_id foreign key (user_id) references users (id),
    constraint ck_shift_pause_intervals_scope check (scope in ('PERSONAL', 'ALL')),
    constraint ck_shift_pause_intervals_target check (
        (scope = 'PERSONAL' and user_id is not null)
        or (scope = 'ALL' and user_id is null)
    ),
    constraint ck_shift_pause_intervals_time_order check (
        ended_at is null or ended_at >= started_at
    )
);

create index idx_shift_pause_intervals_shift_session_id on shift_pause_intervals (shift_session_id);
create index idx_shift_pause_intervals_active_personal on shift_pause_intervals (shift_session_id, scope, user_id, ended_at);
create index idx_shift_pause_intervals_active_scope on shift_pause_intervals (shift_session_id, scope, ended_at);
